{
 "title": "SYM",
 "time": { "from": "2023-07-01T03:00:00.000Z", "to": "2023-07-28T02:59:59.000Z" },
 "panels": [
  {
   "title": "Total income",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select sum(value) as income from sym.amounts where amount_type = 'income' and $__timeFilter(date); "
    }
   ]
  },
  {
   "title": "Balance",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select \n  (select sum(value) as income from sym.amounts where amount_type = 'income' and $__timeFilter(date))\n  -\n  (select sum(value) as expense from sym.amounts where amount_type = 'expense' and $__timeFilter(date));"
    }
   ]
  },
  {
   "title": "Total expense",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyBRL" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select sum(value) as expense from sym.amounts where amount_type = 'expense' and $__timeFilter(date); "
    }
   ]
  },
  {
   "title": "Income x Expense",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select amount_type, sum(value) from sym.amounts WHERE $__timeFilter(date) group by amount_type;"
    }
   ]
  },
  {
   "title": "Income vs Expense",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "select date_format(date,'%Y-%m'), sum(value), amount_type from sym.amounts where $__timeFilter(date)  group by date_format(date,'%Y-%m'), amount_type order by date_format(date,'%Y-%m');"
    }
   ]
  },
  {
   "title": "Expenses by category",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "sym",
     "rawSql": "SELECT category, sum(value) FROM sym.amounts where $__timeFilter(date) and amount_type = 'expense' group by category;"
    }
   ]
  },
  {
   "title": "Expense history by category",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "select date_format(date,'%Y-%m'), sum(value), category from sym.amounts where $__timeFilter(date) and amount_type = 'expense'  group by date_format(date,'%Y-%m'), category order by date_format(date,'%Y-%m');"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "rawSql": "select * from sym.amounts where $__timeFilter(date) order by date desc; "
    }
   ]
  }
 ]
}