services:
  sym:
    image: andrebrisolla/sym:0.6.0
    container_name: sym
    restart: always
    environment:
      MYSQL_HOST: $MYSQL_HOST
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_PORT: $MYSQL_PORT
      MYSQL_DATABASE: $MYSQL_DATABASE
      SPREADSHEETS: $SPREADSHEETS
    volumes:
      - /opt/sym/credentials.json:/app/credentials.json