name: deploy sym
on: workflow_dispatch

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      #- name: Build image container
      #  run: sudo docker build -t sym:latest . --no-cache

      - name: Set creadentials
        run: |
          sed -i "s@${__PRIVATE_KEY__}@${{ secrets.CRED_PRIVATE_KEY }}@g" template_credentials.json