name: deploy sym
on: workflow_dispatch

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Build image container
        run: sudo docker build -t sym:latest . --no-cache

      - name: Start container
        env:
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          MYSQL_HOST: ${{ vars.MYSQL_HOST }}
          MYSQL_USER: ${{ vars.MYSQL_USER }}
          MYSQL_PORT: ${{ vars.MYSQL_PORT }}
          MYSQL_DATABASE: ${{ vars.MYSQL_DATABASE }}
          SPREADSHEETS: ${{ vars.SPREADSHEETS }}
        run: sudo docker compose up -d