name: deploy sym
on: push

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Build image container
        run: sudo docker build -t sym:latest . --no-cache

      - name: Create .env file
        env:
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          MYSQL_HOST: ${{ vars.MYSQL_HOST }}
          MYSQL_USER: ${{ vars.MYSQL_USER }}
          MYSQL_PORT: ${{ vars.MYSQL_PORT }}
          MYSQL_DATABASE: ${{ vars.MYSQL_DATABASE }}
          SPREADSHEETS: ${{ vars.SPREADSHEETS }}
        run: |
          echo "MYSQL_PASSWORD=$MYSQL_PASSWORD" > .env
          echo "MYSQL_HOST=$MYSQL_HOST" >> .env
          echo "MYSQL_USER=$MYSQL_USER" >> .env
          echo "MYSQL_PORT=$MYSQL_PORT" >> .env
          echo "MYSQL_DATABASE=$MYSQL_DATABASE" >> .env
          echo "SPREADSHEETS=$SPREADSHEETS" >> .env

      - name: Start container
        run: sudo docker compose --env-file=.env up -d